[services]
lutris = True
gog = True
humblebundle = True
steam = True

[lutris]
library_ignores = 
migration_version = 10
show_advanced_options = False
width = 927
height = 751
maximized = True
selected_category = category:all
window_x = 45
window_y = 45
view_type = list

[list view]
name_column_width = 414
year_column_width = 250
runner_column_width = 120
platform_column_width = 120
lastplayed_column_width = 120
installedat_column_width = 120
playtime_column_width = 100

