font_family JetBrains Mono Medium Nerd Font Complete
bold_font JetBrains Mono Bold Nerd Font Complete 
italic_font JetBrains Mono Italic Nerd Font Complete
bold_italic_font JetBrains Mono Bold Italic Nerd Font Complete
font_size   12
foreground  #cac0f5
background  #11121d
cursor #9ce5c0
cursor_text_color #29343d
enable_audio_bell no
background_opacity 0.9
shell_integration no_cursor
cursor_shape underline
