font_family Iosevka Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size   13
foreground  #cac0f5
background  #11121d
cursor #9ce5c0
cursor_text_color #29343d
enable_audio_bell no
background_opacity 0.8
shell_integration no_cursor
cursor_shape underline
