#!/bin/sh
alias v=$EDITOR
alias e=exit
alias c=clear
alias ls=exa
alias la="exa -lah"
alias qemu=qemu-system-x86_64
alias farge="farge --notify --no-preview"
alias grim='grim -t jpeg -g "$(slurp)" ~/Pictures/screenshots/'
alias docker='sudo docker'
alias phpMyAdmin='sudo php -S localhost:88 --docroot=/usr/share/webapps/phpMyAdmin'
