TeamViewer User Settings
# It is not recommended to edit this file manually


[int32] LastCorrectorRun = 1
[int32] MainWindowSize = 958 1078 1 961
[int32] OnboardingTaskState = 1 1 1
[bin  ] SUID = 74c90e7b880f4b9b8c7db6cb8d456f6e
[int32] SuitedForOnboarding = 1
